---
name: quran_hadith
description: Qur'an & Hadith
publish_to: none
repository: https://github.com/kherld-hussein/quran_hadith
version: 2.0.7+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  http:
  intl:
  font_awesome_flutter:
  bubble_tab_indicator:
  shimmer:
  shared_preferences:
  auto_size_text:
  lottie:
  provider:
  get: 5.0.0-release-candidate-9.3.2
  adaptive_breakpoints:
  flutter_animated_dialog:
  scroll_to_index:
  animations:
  popover:
  anim_search_bar:
  animated_theme_switcher:
  get_storage:
  platform_device_id:
  process_run:
  # Using media_kit for desktop audio with classic snap confinement
  media_kit: ^1.1.10
  # just_audio for web support
  just_audio: 0.10.5
  just_audio_web: ^0.4.9
  coachmaker:
  desktop_notifications:
  dropdown_button2:
  url_launcher: ^6.0.20
  dio: 5.9.0
  animate_do:
  bitsdojo_window: ^0.1.6
  desktop_window:
  hive:
  hive_flutter:
  menu_bar: ^0.5.2
  # New dependencies for enhanced features
  path_provider: 2.1.5
  file_picker: 10.3.3
  sqflite: ^2.3.0
  flutter_local_notifications: 19.5.0
  hotkey_manager: ^0.2.0
  window_manager: 0.5.1
  connectivity_plus: 7.0.0
  share_plus: 12.0.1
  flutter_markdown: ^0.7.7+1
  cached_network_image: 3.4.1
  fl_chart: 1.1.1
  timezone: 0.10.1
  flutter_native_timezone: ^2.0.0
  package_info_plus: 9.0.0
  rxdart: 0.28.0
  path: ^1.9.0
  ffi: ^2.1.2
  # Priority 1: Native Enhancements
  tray_manager: ^0.5.1
  smtc_windows: ^1.1.0
  flutter_colorpicker: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.1
  hive_generator: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
        - asset: assets/fonts/OpenDyslexic-Italic.otf
        - asset: assets/fonts/OpenDyslexic-Bold-Italic.otf

dependency_overrides:
  win32: ^5.14.0
